=== GollmerSt/TimerImportTool/XML/DVBVTimerImportTool.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
  <xsd:element name="Importer">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="TVInfo" minOccurs="0">
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="Url" type="xsd:string" minOccurs="1"/>
            </xsd:all>
            <xsd:attribute name="username"      type="xsd:string" use="required"/>
            <xsd:attribute name="password"      type="xsd:string" use="required"/>
            <xsd:attribute name="triggeraction" type="xsd:integer"/>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="DVBService" minOccurs="0">
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="WakeOnLAN" minOccurs="0">
                <xsd:complexType>
                  <xsd:attribute name="enable"           type="xsd:boolean" use="required"/>
                  <xsd:attribute name="broadCastaddress" type="xsd:string" use="required"/>
                  <xsd:attribute name="macAddress"       type="myMacType" use="required"/>
                  <xsd:attribute name="waitTimeAfterWOL" type="xsd:integer"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:all>
            <xsd:attribute name="url"      type="xsd:string" use="required"/>
            <xsd:attribute name="username" type="xsd:string" use="required"/>
            <xsd:attribute name="password" type="xsd:string" use="required"/>
            <xsd:attribute name="timeZone" type="xsd:string" use="required"/>
          </xsd:complexType>
        </xsd:element>
      
        <xsd:element name="Offsets" type="myOffsetsType" minOccurs="0"/>
        <xsd:element name ="Combine"   type="xsd:string" minOccurs="0"/>
        <xsd:element name ="Separator" type="xsd:string" minOccurs="0"/>

        <xsd:element name="Channels" minOccurs="1">
          <xsd:complexType>
                        <xsd:sequence>
              <xsd:element name="Channel" maxOccurs="unbounded" minOccurs="1">
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element name="TVInfo" type="xsd:string" minOccurs="0" />
                    <xsd:element name="ClickFinder" type="xsd:string" minOccurs="0" />
                    <xsd:element name="DVBViewer" type="myDVBViewerChannelType" />
                    <xsd:element name="Offsets" type="myOffsetsType" minOccurs="0" />
                    <xsd:element name="Combine" type="xsd:boolean" minOccurs="0" />
                  </xsd:all>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:all>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="myTimeType">
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='\d{2}\:\d{2}'/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="myDaysType">
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='[01]{7}'/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="myMacType">
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='(\d{2}[\-:]){5}\d{2}'/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="myDVBViewerChannelType">
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='(\d+\|.*)|(none)'/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="myOffsetsType">
        <xsd:sequence>
      <xsd:element name="Offset" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="before" type="xsd:integer" />
          <xsd:attribute name="after" type="xsd:integer" />
          <xsd:attribute name="days" type="myDaysType" />
          <xsd:attribute name="begin" type="myTimeType" />
          <xsd:attribute name="end" type="myTimeType" />
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


</xsd:schema>

=== GollmerSt/TimerImportTool/XML/DVBVTimerImportTool.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Importer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DVBVTimerImportTool.xsd">
    <TVInfo
        username="DVBViewerImport"
        password="TimerImportTool"
        triggeraction="16640">
        <Url>http://www.tvinfo.de/share/openepg/schedule.php</Url>
    </TVInfo>
    <DVBService
        url="localhost:50425"
        username="admin"
        password="admin"
        timeZone="Europe/Berlin">
    </DVBService>
    <Offsets>
        <Offset before="15"/>
        <Offset after="30"/>
    </Offsets>
    <Combine>true</Combine>
    <Separator>,,</Separator>
    <Channels>
        <Channel>
            <TVInfo>ARD</TVInfo>
            <ClickFinder>ARD</ClickFinder>
            <DVBViewer>543583690|Das Erste (deu)</DVBViewer>
            <Offsets>
                <Offset after="60" days="0000011" begin="22:00"/>
                <Offset after="60" days="1000001" begin="00:00" end="04:00"/>
            </Offsets>
            <Combine>false</Combine>
        </Channel>
        <Channel>
            <TVInfo>ZDF</TVInfo>
            <ClickFinder>ZDF</ClickFinder>
            <DVBViewer>544763238|ZDF (deu)</DVBViewer>
            <Offsets>
                <Offset after="60" days="0000011" begin="22:00"/>
                <Offset after="60" days="1000001" begin="00:00" end="04:00"/>
            </Offsets>
        </Channel>
        <Channel>
            <TVInfo>Bayern</TVInfo>
            <ClickFinder>B3</ClickFinder>
            <DVBViewer>550137291|Bayerisches FS Süd (deu)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>HR</TVInfo>
            <ClickFinder>H3</ClickFinder>
            <DVBViewer>550137291|Bayerisches FS Süd (deu)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>WDR</TVInfo>
            <ClickFinder>WDR</ClickFinder>
            <DVBViewer>576351695|WDR Köln</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>SWR</TVInfo>
            <ClickFinder>SWR</ClickFinder>
            <DVBViewer>740191815|SWR Fernsehen RP</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>MDR</TVInfo>
            <ClickFinder>MDR</ClickFinder>
            <DVBViewer>727150150|MDR Thüringen (2ch)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>NDR</TVInfo>
            <ClickFinder>NDR</ClickFinder>
            <DVBViewer>707423809|NDR FS HH (2ch)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>RBB</TVInfo>
            <ClickFinder>RBB</ClickFinder>
            <DVBViewer>576351790|rbb Berlin</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Ki.Ka</TVInfo>
            <ClickFinder>Ki.Ka</ClickFinder>
            <DVBViewer>557870440|KiKa</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>3sat</TVInfo>
            <ClickFinder>3SAT</ClickFinder>
            <DVBViewer>551316839|3sat (deu)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>SR</TVInfo>
            <DVBViewer>622227270|SR Fernsehen</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Alpha</TVInfo>
            <ClickFinder>BR Alpha</ClickFinder>
            <DVBViewer>628780871|BR-alpha</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>ORF2</TVInfo>
            <ClickFinder>ORF 2</ClickFinder>
            <DVBViewer>747962478|ORF2</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Tele 5</TVInfo>
            <ClickFinder>Tele5</ClickFinder>
            <DVBViewer>637534319|TELE 5</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Sat1</TVInfo>
            <ClickFinder>SAT1</ClickFinder>
            <DVBViewer>553665628|SAT.1</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Kabel1</TVInfo>
            <ClickFinder>Kabel</ClickFinder>
            <DVBViewer>587220062|kabel eins</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Pro7</TVInfo>
            <ClickFinder>PRO7</ClickFinder>
            <DVBViewer>570442845|ProSieben</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>RTL</TVInfo>
            <ClickFinder>RTL</ClickFinder>
            <DVBViewer>543698659|RTL Television</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>RTL2</TVInfo>
            <ClickFinder>RTL II</ClickFinder>
            <DVBViewer>545271540|RTL2</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Super RTL</TVInfo>
            <ClickFinder>S RTL</ClickFinder>
            <DVBViewer>544747272|Super RTL</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>VOX</TVInfo>
            <ClickFinder>VOX</ClickFinder>
            <DVBViewer>545795868|VOX</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>arte</TVInfo>
            <ClickFinder>Arte</ClickFinder>
            <DVBViewer>563245108|arte (ger)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Das Vierte</TVInfo>
            <ClickFinder>Das Vierte</ClickFinder>
            <DVBViewer>671088743|DAS VIERTE</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>9 Live</TVInfo>
            <ClickFinder>9Live</ClickFinder>
            <DVBViewer>620774496|9Live</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>BBC</TVInfo>
            <ClickFinder>BBC</ClickFinder>
            <DVBViewer>542900425|BBC World</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>BloombergTV</TVInfo>
            <ClickFinder>BloombergTV</ClickFinder>
            <DVBViewer>629932133|Bloomberg German TV</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>CNBC</TVInfo>
            <DVBViewer>557056202|CNBC Europe</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>CNN</TVInfo>
            <ClickFinder>CNN</ClickFinder>
            <DVBViewer>543424715|CNN Int.</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Comedy Central</TVInfo>
            <ClickFinder>Comedy Central</ClickFinder>
            <DVBViewer>803733606|COMEDY CENTRAL Germany</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>DSF</TVInfo>
            <ClickFinder>DSF</ClickFinder>
            <DVBViewer>603979880|DSF</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>EinsExtra</TVInfo>
            <ClickFinder>EinsExtra</ClickFinder>
            <DVBViewer>543584305|EinsExtra</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>EinsFestival</TVInfo>
            <ClickFinder>EinsFestival</ClickFinder>
            <DVBViewer>550137906|EinsFestival</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>EinsPlus</TVInfo>
            <ClickFinder>EinsMuXx</ClickFinder>
            <DVBViewer>556691507|EinsPlus</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>N24</TVInfo>
            <ClickFinder>N24</ClickFinder>
            <DVBViewer>603997279|N24</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>n-tv</TVInfo>
            <ClickFinder>NTV</ClickFinder>
            <DVBViewer>541667130|n-tv</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Phoenix</TVInfo>
            <ClickFinder>Phoenix</ClickFinder>
            <DVBViewer>569798709|Phoenix</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>EuroNews</TVInfo>
            <ClickFinder>EURONEWS</ClickFinder>
            <DVBViewer>696320204|EuroNews (ger)</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Eurosport</TVInfo>
            <ClickFinder>EUROSPORT</ClickFinder>
            <DVBViewer>543621325|Eurosport</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Home Shopping Europe</TVInfo>
            <ClickFinder>Home Shopping Europe</ClickFinder>
            <DVBViewer>620757198|HSE</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>MTV</TVInfo>
            <ClickFinder>MTV</ClickFinder>
            <DVBViewer>801112170|MTV Germany</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>münchen 2</TVInfo>
            <ClickFinder>münchen 2</ClickFinder>
            <DVBViewer>550109291|Muenchen2</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>münchen.tv</TVInfo>
            <DVBViewer>539295852|MuenchenTV</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>Nick</TVInfo>
            <ClickFinder>Nick</ClickFinder>
            <DVBViewer>805699693|NICK Germany</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>RTLSHOP</TVInfo>
            <ClickFinder>RTL Shop</ClickFinder>
            <DVBViewer>545861424|RTL Shop</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>TRT</TVInfo>
            <ClickFinder>TRT</ClickFinder>
            <DVBViewer>83598289|TRT Int. - CV</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>VIVA</TVInfo>
            <ClickFinder>VIVA</ClickFinder>
            <DVBViewer>803078256|VIVA Germany</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>ZDFinfokanal</TVInfo>
            <ClickFinder>ZDFInfo</ClickFinder>
            <DVBViewer>577531243|ZDFinfokanal</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>ZDFtheaterkanal</TVInfo>
            <ClickFinder>ZDF Theaterkanal</ClickFinder>
            <DVBViewer>610299248|ZDFtheaterkanal</DVBViewer>
        </Channel>
        <Channel>
            <TVInfo>ZDF_neo</TVInfo>
            <ClickFinder>ZDFneo</ClickFinder>
            <DVBViewer>580808046|ZDFdokukanal (deu)</DVBViewer>
        </Channel>
