=== GollmerSt/TimerImportTool/XML/DVBVTimerImportPrcd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xsd:element name="Processed">
      <xsd:complexType>
      	<xsd:sequence>
      		<xsd:element name="Entry" minOccurs="0"
      			maxOccurs="unbounded" type="DVBViewerEntry">
      		</xsd:element>
      	</xsd:sequence>
      	<xsd:attribute name="version" type="xsd:int"></xsd:attribute>
      </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="DVBViewerEntry">
    	<xsd:sequence>
    		<xsd:element name="Title" type="xsd:string" minOccurs="1"
    			maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="MergedWith" minOccurs="0"
    			maxOccurs="1">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="Id" type="xsd:int"
    						maxOccurs="unbounded" minOccurs="0">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:sequence>

    	<xsd:attribute name="id" type="long" use="required"></xsd:attribute>
    	<xsd:attribute name="isFilterElement" type="xsd:boolean"
    		use="required">
    		<xsd:annotation>
    			<xsd:documentation>
    				Is set if entry is generated by the merge algorithm
    			</xsd:documentation>
    		</xsd:annotation>
    	</xsd:attribute>
    	<xsd:attribute name="statusService" use="required">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="ENABLED"></xsd:enumeration>
    				<xsd:enumeration value="DISABLED"></xsd:enumeration>
    				<xsd:enumeration value="REMOVED"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="channel" type="myDVBViewerChannelType"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="start" type="long" use="required"></xsd:attribute>
    	<xsd:attribute name="end" type="long" use="required"></xsd:attribute>
    	<xsd:attribute name="startOrg" type="long" use="required"></xsd:attribute>
    	<xsd:attribute name="endOrg" type="long" use="required"></xsd:attribute>
    	<xsd:attribute name="canMerge" type="xsd:boolean"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="mergeID" type="long" use="optional"></xsd:attribute>
    	<xsd:attribute name="provider" use="optional">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="TVInfo"></xsd:enumeration>
    				<xsd:enumeration value="ClickFinder"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="missingSince" type="long"
    		use="optional">
    	</xsd:attribute>
    	<xsd:attribute name="missingSyncSince" type="xsd:int"
    		use="optional">
    	</xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="myDVBViewerChannelType">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="(\d+\|.*)"></xsd:pattern>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="long">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="(-)?\d+"></xsd:pattern>
    	</xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== GollmerSt/TimerImportTool/XML/DVBVTimerImportPrcd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Processed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DVBVTimerImportPrcd.xsd">
    <Entry id="32" isFilterElement="true" statusService="ENABLED" channel="557870440|KiKa" start="1271327760000" end="1271330700000" startOrg="1271328660000" endOrg="1271328900000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Classic Cartoon - Der rosarote Panther: Der rosarote Hundeschreck</Title>
    </Entry>
    <Entry id="33" isFilterElement="true" statusService="ENABLED" channel="545795868|VOX" start="1271354400000" end="1271364300000" startOrg="1271355300000" endOrg="1271362500000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Der Flug des Phoenix</Title>
    </Entry>
    <Entry id="34" isFilterElement="true" statusService="ENABLED" channel="557870440|KiKa" start="1271414160000" end="1271417100000" startOrg="1271415060000" endOrg="1271415300000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Classic Cartoon - Der rosarote Panther: Der rosarote Fotoschreck</Title>
    </Entry>
    <Entry id="35" isFilterElement="true" statusService="ENABLED" channel="545795868|VOX" start="1271425500000" end="1271435400000" startOrg="1271426400000" endOrg="1271433600000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Der Flug des Phoenix</Title>
    </Entry>
    <Entry id="36" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271454300000" end="1271458800000" startOrg="1271455200000" endOrg="1271457000000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>WAS GUCKST DU?!</Title>
    </Entry>
    <Entry id="37" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271456100000" end="1271460300000" startOrg="1271457000000" endOrg="1271458500000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>WAS GUCKST DU?!</Title>
    </Entry>
    <Entry id="38" isFilterElement="true" statusService="ENABLED" channel="570442845|ProSieben" start="1271494500000" end="1271499000000" startOrg="1271495400000" endOrg="1271497200000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>TRAMITZ and friends</Title>
    </Entry>
    <Entry id="39" isFilterElement="true" statusService="ENABLED" channel="570442845|ProSieben" start="1271496300000" end="1271500800000" startOrg="1271497200000" endOrg="1271499000000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Bully &amp; Rick - Call Center</Title>
    </Entry>
    <Entry id="40" isFilterElement="true" statusService="ENABLED" channel="671088743|DAS VIERTE" start="1271527200000" end="1271537400000" startOrg="1271528100000" endOrg="1271535600000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Der gezähmte Widerspenstige</Title>
    </Entry>
    <Entry id="41" isFilterElement="true" statusService="ENABLED" channel="543583690|Das Erste (deu)" start="1271568300000" end="1271574000000" startOrg="1271569200000" endOrg="1271572200000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Meister Eder und sein Pumuckl - Das Spielzeugauto / Pumuckl und die Obstbäume</Title>
    </Entry>
    <Entry id="42" isFilterElement="true" statusService="ENABLED" channel="544763238|ZDF (deu)" start="1271571600000" end="1271575800000" startOrg="1271572500000" endOrg="1271574000000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Löwenzahn - Ratten - Der Fänger von Bärstadt</Title>
    </Entry>
    <Entry id="43" isFilterElement="true" statusService="ENABLED" channel="628780871|BR-alpha" start="1271577600000" end="1271582100000" startOrg="1271578500000" endOrg="1271580300000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Bibliothek der Sachgeschichten - P (3) - wie Pumpe, Putzer, Printen, Pudel trimmen und Pflasterstein</Title>
    </Entry>
    <Entry id="44" isFilterElement="true" statusService="ENABLED" channel="556690892|hr-fernsehen (deu)" start="1271581200000" end="1271586600000" startOrg="1271582100000" endOrg="1271584800000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Georg Ringsgwandl - Kasperl oder Genie? Kabarettist!</Title>
    </Entry>
    <Entry id="45" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271583900000" end="1271588100000" startOrg="1271584800000" endOrg="1271586300000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>WAS GUCKST DU?!</Title>
    </Entry>
    <Entry id="46" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271585400000" end="1271589900000" startOrg="1271586300000" endOrg="1271588100000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>WAS GUCKST DU?!</Title>
    </Entry>
    <Entry id="47" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271587200000" end="1271591700000" startOrg="1271588100000" endOrg="1271589900000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Mensch Markus</Title>
    </Entry>
    <Entry id="48" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271589000000" end="1271593500000" startOrg="1271589900000" endOrg="1271591700000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Mensch Markus</Title>
    </Entry>
    <Entry id="49" isFilterElement="true" statusService="ENABLED" channel="587220062|kabel eins" start="1271589300000" end="1271597700000" startOrg="1271590200000" endOrg="1271595900000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Ödipussi</Title>
    </Entry>
    <Entry id="50" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1271598000000" end="1271602500000" startOrg="1271598900000" endOrg="1271600700000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>DIE DREISTEN DREI - DIE COMEDY WG</Title>
    </Entry>
    <Entry id="51" isFilterElement="true" statusService="ENABLED" channel="557870440|KiKa" start="1271598300000" end="1271602500000" startOrg="1271599200000" endOrg="1271600700000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Löwenzahn - Ratten - Der Fänger von Bärstadt</Title>
    </Entry>
    <Entry id="52" isFilterElement="true" statusService="ENABLED" channel="563245108|arte (ger)" start="1271988300000" end="1271992800000" startOrg="1271989200000" endOrg="1271991000000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Rien ne va plus</Title>
    </Entry>
    <Entry id="53" isFilterElement="true" statusService="ENABLED" channel="544747272|Super RTL" start="1272045600000" end="1272055500000" startOrg="1272046500000" endOrg="1272053700000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Wallace &amp; Gromit : Auf Leben und Brot</Title>
    </Entry>
    <Entry id="54" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1272045600000" end="1272056700000" startOrg="1272046500000" endOrg="1272054900000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>Die Comedy-Falle</Title>
    </Entry>
    <Entry id="55" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1272059100000" end="1272063600000" startOrg="1272060000000" endOrg="1272061800000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>WAS GUCKST DU?!</Title>
    </Entry>
    <Entry id="56" isFilterElement="true" statusService="ENABLED" channel="553665628|SAT.1" start="1272060900000" end="1272065400000" startOrg="1272061800000" endOrg="1272063600000" timerAction="RECORD" actionAfter="HIBERNATE" mergeStatus="DISABLED" provider="TVInfo" enable="false" missingSince="-1" missingSyncSince="0">
        <Title>WAS GUCKST DU?!</Title>
